# Generated by Django 5.1.6 on 2025-02-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carselection',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carselection',
            name='selected_at',
        ),
        migrations.AddField(
            model_name='carselection',
            name='car_brand',
            field=models.CharField(default='DefaultBrand', max_length=255),
        ),
        migrations.AddField(
            model_name='carselection',
            name='car_model',
            field=models.CharField(default='DefaultModel', max_length=255),
        ),
        migrations.AddField(
            model_name='carselection',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='carselection',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='carselection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
